<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStoreUsersTable extends Migration
{
    
    public function up()
    {
        DB::table('users')->truncate();
        DB::table('users')->insert([
            [
            'name' => 'admin',
            'email' => 'admin@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Administrator',
            'faculty_id' => null,
            'department_id' => null,
            'dob'=>'1980-02-12',
            'gender' => 'male',
            ],
            [
            'name' => 'manager',
            'email' => 'manager@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'EC Manager',
            'faculty_id' => null,
            'department_id' => null,
            'dob'=>'1985-02-12',
            'gender' => 'male',
            ],
           
            // Faculty of Business & Economics -> EC Coordinator 
             [
            'name' => 'Business and Econmonic',
            'email' => 'fac_bc@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'EC Coordinator',
            'faculty_id' => '1',
            'department_id' => null,
            'dob'=>'1980-02-12',
            'gender' => 'female',
            ],

            // Department of Business Administration -> Student 
            [
            'name' => 'BA Student 01',
            'email' => 'stu_ba@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' => '1',
            'dob'=>'1992-02-12',
            'gender' => 'male',
            ],
           [
            'name' => 'BA Student 02',
            'email' => 'stu_ba02@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' => '1',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
            [
            'name' => 'BA Student 03',
            'email' => 'stu_ba03@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' => '1',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'BA Student 04',
                'email' => 'stu_ba04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' => '1',
                'dob'=>'1992-06-12',
                'gender' => 'female',
            ],
            // Department of Tourism & Hospitality Management -> Student
            [
            'name' => 'Tourism Student',
            'email' => 'stu_thm@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'2',
            'dob'=>'1994-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'Tourism Student 02',
                'email' => 'stu_thm_02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'2',
                'dob'=>'1994-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'Tourism Student 03',
                'email' => 'stu_thm_03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'2',
                'dob'=>'1994-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'Tourism Student 04',
                'email' => 'stu_thm_04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'2',
                'dob'=>'1994-02-12',
                'gender' => 'male',
            ],
          
            // Department of Real Estate -> Student
            [
            'name' => 'RE Student',
            'email' => 'stu_re@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'3',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'RE Student 02',
                'email' => 'stu_re02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'3',
                'dob'=>'1992-02-12',
                'gender' => 'female',
            ],[
                'name' => 'RE Student 03',
                'email' => 'stu_re03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'3',
                'dob'=>'1992-02-12',
                'gender' => 'male',
            ],[
                'name' => 'RE Student 04',
                'email' => 'stu_re04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'3',
                'dob'=>'1992-02-12',
                'gender' => 'female',
            ],
            // Faculty of Science and Information Technology -> EC Coordinator  
             [
            'name' => 'Siplu Sir',
            'email' => 'siplu_sir@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'EC Coordinator',
            'faculty_id' => '2',
            'department_id' => null,
            'dob'=>'1986-02-12',
            'gender' => 'male',
            ],
            
            // Department of Business Information Technology (BIT) --> Students 
           
           [
            'name' => 'moshiur',
            'email' => 'moshiur@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'4',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
             [
            'name' => 'BIT Student',
            'email' => 'stu_bit@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'4',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
             [
            'name' => 'BIT Student 02',
            'email' => 'stu_bit02@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'4',
            'dob'=>'1992-02-12',
            'gender' => 'male',
            ],
             [
            'name' => 'BIT Student 03',
            'email' => 'stu_bit03@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'4',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],

            [
            'name' => 'BIT Student 04',
            'email' => 'stu_bit04@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'4',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
            
            // Department of Computer Science and Engineering
            [
            'name' => 'CSE Student',
            'email' => 'stu_cse@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'5',
            'dob'=>'1995-02-12',
            'gender' => 'male',
            ],
            [
                'name' => 'CSE Student 02',
                'email' => 'stu_cse02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'5',
                'dob'=>'1995-02-12',
                'gender' => 'female',
            ],[
                'name' => 'CSE Student 03',
                'email' => 'stu_cse03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'5',
                'dob'=>'1995-02-12',
                'gender' => 'male',
            ],[
                'name' => 'CSE Student 04',
                'email' => 'stu_cse04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'5',
                'dob'=>'1995-02-12',
                'gender' => 'female',
            ],
             // Department of Software Engineering
            [
            'name' => 'SE Student',
            'email' => 'stu_se@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'6',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'SE Student 02',
                'email' => 'stu_se02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'6',
                'dob'=>'1992-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'SE Student 03',
                'email' => 'stu_se03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'6',
                'dob'=>'1992-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'SE Student 04',
                'email' => 'stu_se04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'6',
                'dob'=>'1992-02-12',
                'gender' => 'male',
            ],
             // Department of Multimedia & Creative Technology (MCT)
            [
            'name' => 'MCT Student',
            'email' => 'stu_mct@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'7',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'MCT Student 02',
                'email' => 'stu_mct02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'7',
                'dob'=>'1992-02-12',
                'gender' => 'male',
            ],[
                'name' => 'MCT Student 03',
                'email' => 'stu_mct03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'7',
                'dob'=>'1992-02-12',
                'gender' => 'male',
            ],[
                'name' => 'MCT Student 04',
                'email' => 'stu_mct04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'7',
                'dob'=>'1992-02-12',
                'gender' => 'female',
            ],

               // Faculty of Engineering -> EC Coordinator 
            [
            'name' => 'Engineering',
            'email' => 'fac_eng@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'EC Coordinator',
            'faculty_id' => '3',
            'department_id' => null,
            'dob'=>'1980-02-12',
            'gender' => 'male',
            ],

            // Department of Electronics and Telecommunication Engineering -> student
            [
            'name' => 'ETC Student',
            'email' => 'stu_etc@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'8',
            'dob'=>'1992-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'ETC Student 02',
                'email' => 'stu_etc02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'8',
                'dob'=>'1992-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'ETC Student 03',
                'email' => 'stu_etc03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'8',
                'dob'=>'1992-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'ETC Student 04',
                'email' => 'stu_etc04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'8',
                'dob'=>'1992-02-12',
                'gender' => 'female',
            ],

            // Department of Textile Engineering ->student
            [
            'name' => 'TE Student',
            'email' => 'stu_te@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'9',
            'dob'=>'1993-02-12',
            'gender' => 'male',
            ],
            [
                'name' => 'TE Student 02',
                'email' => 'stu_te02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'9',
                'dob'=>'1993-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'TE Student 03',
                'email' => 'stu_te03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'9',
                'dob'=>'1993-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'TE Student 04',
                'email' => 'stu_te04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'9',
                'dob'=>'1993-02-12',
                'gender' => 'male',
            ],

             // Department of Civil Engineering -> student
            [
            'name' => 'CE Student',
            'email' => 'stu_ce@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'10',
            'dob'=>'1996-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'CE Student 02',
                'email' => 'stu_ce02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'10',
                'dob'=>'1996-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'CE Student 03',
                'email' => 'stu_ce03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'10',
                'dob'=>'1996-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'CE Student 04',
                'email' => 'stu_ce04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'10',
                'dob'=>'1996-02-12',
                'gender' => 'male',
            ],

                // Faculty of Allied Health Science -> EC Coordinator 
             [
            'name' => 'Allied Health Science',
            'email' => 'fac_ahs@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'EC Coordinator',
            'faculty_id' => '4',
            'department_id' => null,
            'dob'=>'1980-02-12',
            'gender' => 'female',
            ],

             // Department of Pharmacy -> student
            [
            'name' => 'Pharmacy Student',
            'email' => 'stu_ph@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'11',
            'dob'=>'1990-02-12',
            'gender' => 'male',
            ],
            [
                'name' => 'Pharmacy Student 02',
                'email' => 'stu_ph02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'11',
                'dob'=>'1990-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'Pharmacy Student 03',
                'email' => 'stu_ph03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'11',
                'dob'=>'1990-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'Pharmacy Student 04',
                'email' => 'stu_ph04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'11',
                'dob'=>'1990-02-12',
                'gender' => 'female',
            ],

            // Department of Nutrition and Food Engineering ->student
            [
            'name' => 'NFE Student',
            'email' => 'stu_nfe@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'12',
            'dob'=>'1989-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'NFE Student 02',
                'email' => 'stu_nfe02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'12',
                'dob'=>'1989-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'NFE Student 03',
                'email' => 'stu_nfe03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'12',
                'dob'=>'1989-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'NFE Student 04',
                'email' => 'stu_nfe04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'12',
                'dob'=>'1989-02-12',
                'gender' => 'male',
            ],

            // Department of Public Health -> student 
            [ 
            'name' => 'PH Student',
            'email' => 'stu_pubh@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'13',
            'dob'=>'1991-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'PH Student 02',
                'email' => 'stu_pubh02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'13',
                'dob'=>'1991-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'PH Student 03',
                'email' => 'stu_pubh03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'13',
                'dob'=>'1991-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'PH Student 04',
                'email' => 'stu_pubh04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'13',
                'dob'=>'1991-02-12',
                'gender' => 'male',
            ],

     // Faculty of Humanities & Social Science -> EC Coordinator 
             [
            'name' => 'Humanities & Social Science',
            'email' => 'fac_hss@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'EC Coordinator',
            'faculty_id' => '5',
            'department_id' => null,
            'dob'=>'1980-02-12',
            'gender' => 'female',
            ],

             // Department of English -> student 
            [
            'name' => 'English Student',
            'email' => 'stu_eng@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'14',
            'dob'=>'1993-02-12',
            'gender' => 'female',
            ],
            [
                'name' => 'English Student 02',
                'email' => 'stu_eng02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'14',
                'dob'=>'1993-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'English Student 03',
                'email' => 'stu_eng03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'14',
                'dob'=>'1993-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'English Student 04',
                'email' => 'stu_eng04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'14',
                'dob'=>'1993-02-12',
                'gender' => 'female',
            ],

            // Department of Law -> student
            [
            'name' => 'Law Student',
            'email' => 'stu_law@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'15',
            'dob'=>'1993-02-12',
            'gender' => 'male',
            ],
            [
                'name' => 'Law Student 02',
                'email' => 'stu_law02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'15',
                'dob'=>'1993-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'Law Student 03',
                'email' => 'stu_law03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'15',
                'dob'=>'1993-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'Law Student 04',
                'email' => 'stu_law04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'15',
                'dob'=>'1993-02-12',
                'gender' => 'female',
            ],

             // Department of Journalism & Mass Communication -> student
            [
            'name' => 'JMC Student',
            'email' => 'stu_jmc@gmail.com',
            'password' => bcrypt('123456'),
            'role' => 'Student',
            'faculty_id' => null,
            'department_id' =>'16',
            'dob'=>'1993-02-12',
            'gender' => 'male',
            ],
            [
                'name' => 'JMC Student 02',
                'email' => 'stu_jmc02@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'16',
                'dob'=>'1993-02-12',
                'gender' => 'female',
            ],
            [
                'name' => 'JMC Student 03',
                'email' => 'stu_jmc03@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'16',
                'dob'=>'1993-02-12',
                'gender' => 'male',
            ],
            [
                'name' => 'JMC Student 04',
                'email' => 'stu_jmc04@gmail.com',
                'password' => bcrypt('123456'),
                'role' => 'Student',
                'faculty_id' => null,
                'department_id' =>'16',
                'dob'=>'1993-02-12',
                'gender' => 'female',
            ],

            ]);
}

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
